version: 2

jobs:
  build:
    docker:
      - image: ammaratef45/flutter:v2
    steps:
      - checkout
      - run: flutter doctor
      - run: cd attendance && flutter packages get && dartanalyzer --options analysis_options.yaml .
      - run: cd attendance && chmod +x cleanENV.sh && ./cleanENV.sh && ls && cat firebase_token_generator.py && flutter test --coverage
